### ISSUE TITLE
https://docs.open-systems-pharmacology.org/ not working anymore

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/docs#103]
The link to the OSP manual is broken:
https://docs.open-systems-pharmacology.org/

**Comment by msevestre** [comment]
https://twitter.com/tmjee/status/1268450345648152577

gitbook is down. Our docs will be back when the issue is solved

**Comment by msevestre** [comment]
https://twitter.com/msmichellegar/status/1268495351771803648

**Comment by PavelBal** [comment]
Maybe for such cases, it would be a good idea to include a PDF-version of the documentation with each release? Could make a note that the up-to-date docu is available online, but there still will be an emergency solution.

**Comment by msevestre** [comment]
Well it is in the release :) open-systems-pharmacology.pdf

**Comment by msevestre** [comment]
It's just not very pretty. But for emergency...does the job

**Comment by msevestre** [comment]
back live
