### ISSUE TITLE
Pk-sim documentation citation. 

### ISSUE THREAD

**Issue by AnisPBPK** [Open-Systems-Pharmacology/docs#108]
Hello, 
Can some one give me the citation of PK-sim guideline, I need to put it in my report reference. 
Thank you in advance

**Comment by Yuri05** [comment]
Do you mean this one? 
https://docs.open-systems-pharmacology.org/

**Comment by AnisPBPK** [comment]
Yes Mr Yuri, I mean this one. 

> Do you mean this one?
> https://docs.open-systems-pharmacology.org/

**Comment by Yuri05** [comment]
Well, you can refer to it e.g. as **OSP Suite documentation**
