### ISSUE TITLE
Issue with createPopulation

### ISSUE THREAD

**Issue by kmjob** [Open-Systems-Pharmacology/docs#124]
Hello,

While trying to run a simulation using the ospsuite R-package, I ran into an issue with creating a population (P_pop). When I use createPopulation, I think it is creating a list instead of a population. Typing "P_pop$" only gives a couple options and when I try to run the simulation I get the error below.

Error in validateIsOfType(population, Population, nullAllowed = TRUE) : 
  runSimulation: argument 'population' is of type 'list', but expected 'Population'!

Attached is a screenshot of my console. Has anyone run in to this issue before?

Thank you,
Kate

![image](https://user-images.githubusercontent.com/78875331/107685043-c1433700-6c60-11eb-9be2-e88e0546c795.png)

**Comment by msevestre** [comment]
@AndreDlm Which version of ospsuite-r are you using?

**Comment by msevestre** [comment]
@Yuri05  How do you update the docs to have the latest vignettes?

**Comment by AndreDlm** [comment]
> @AndreDlm Which version of ospsuite-r are you using?

v 9.0.79

**Comment by kmjob** [comment]
Thank you all: this worked! I will take closer look at the vignettes.

**Comment by msevestre** [comment]
@AndreDlm Yes this is outdated
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/tag/v9.1.4

9.1 is the official first release and is not compatible with 9.0 on exactly this use case :)

**Comment by AndreDlm** [comment]
Thanks @msevestre

**Comment by msevestre** [comment]
@PavelBal I agree with you. I think the runSimulation should also support this object as parameter and extract the population if required. This would be just a better UX. I am going to create an issue for this

**Comment by msevestre** [comment]
@PavelBal @AndreDlm This will be available in the next version of ospuite-r (either population or result fo create population) would work

**Comment by Yuri05** [comment]
updated to latest vignettes in V10 docu
