### ISSUE TITLE
Unclear statement?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/docs#128]
https://docs.open-systems-pharmacology.org/open-systems-pharmacology-suite/modules-philsophy-building-blocks#mobi-r
Somehow the last sentence at the end of the 2nd paragraph (_Refine a Reaction(s) network and update it in all tissues where it should be considered._) does not make sense in this context - or is it just my impression?

**Comment by PavelBal** [comment]
It sounds like a list of bullet points for topics that should be expanded, but never were.
