### ISSUE TITLE
Update docu of P-gp

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/docs#132]
- Add the statement that it should not be used...

- 4.	Dokumentation: P-gp: Transport „von Interstital nach Interstital“ verdient noch eine Erklärung bzw. Umformulierung.

**Comment by PavelBal** [comment]
I don't know whether it should also be done in PK-Sim GUI.

**Comment by msevestre** [comment]
Updating as deprecated

**Comment by msevestre** [comment]
THis is done in v11
