### ISSUE TITLE
update ospsuite-r docu

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/docs#144]
from vignettes of ospsuite-r 10

**Comment by msevestre** [comment]
done with link to website

**Comment by Yuri05** [comment]
I wonder if we can change the order of the articles. At the moment it's random(?)
![grafik](https://user-images.githubusercontent.com/25061876/135531791-d2b1e6c6-66fe-4454-85e6-af1eade2c1b0.png)
Would be nice to have the logical order:
* Introduction
* Loading a simulation
* Changing parameter and molecule start values
* Running a simulation
* ...

**Comment by msevestre** [comment]
based on this
![image](https://user-images.githubusercontent.com/1041237/135532702-fc2c7191-21cb-4452-b1cf-b27584cfdf60.png)

**Comment by omachala** [comment]
Hi! I can help update these screenshots.

I maintain [heroshot](https://heroshot.sh), a screenshot automation tool that captures screenshots from a config file using Playwright. Makes documentation maintenance easier.

Happy to submit a PR!
