### ISSUE TITLE
minimum needed R version

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/docs#156]
https://docs.open-systems-pharmacology.org/open-systems-pharmacology-suite/getting-started

This says the minimum version can either be `3.5` or `3.6`, but that can't be right. If the minimum required version is `3.6`, then the package would not work with `3.5`. 

So which one is it?

**Comment by msevestre** [comment]
Minimum version is wrong. Moving to docs repo where it belongs

**Comment by msevestre** [comment]
Yes sure. But the R package specifies (README) that it works with 3.6 and above. I think the doc is the only place where it is wrong? Or am I missing something?

**Comment by IndrajeetPatil** [comment]
> I think the doc is the only place where it is wrong?

Yepp, I think that's the only thing that needs to be changed.

I guess it's just a matter of personal taste whether to explicitly declare the minimum needed R version in the package description itself or mention it in the README.

**Comment by msevestre** [comment]
this is done

**Comment by msevestre** [comment]
Ithink this is done
