### ISSUE TITLE
"Scaling method" section not rendered properly in the git book

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/docs#159]
Although this looks fine in the underlying `.md` [file](https://github.com/Open-Systems-Pharmacology/docs/blob/v10/part-3/pk-sim-creating-individuals.md):

![image](https://user-images.githubusercontent.com/11330453/135471964-b9013bfc-a0cb-4dad-900d-44761ab23230.png)

In the [git book](https://docs.open-systems-pharmacology.org/v/v10/working-with-pk-sim/pk-sim-documentation/pk-sim-creating-individuals), subitems are displayed as items, which is really confusing for the reader:

![image](https://user-images.githubusercontent.com/11330453/135471776-e14df96a-fea3-48fd-927e-691e87b96d0a.png)

**Comment by msevestre** [comment]
wow..good find

**Comment by msevestre** [comment]
boom
![image](https://user-images.githubusercontent.com/1041237/135525457-67086948-0d73-41eb-93db-a45bc92a5bff.png)

**Comment by IndrajeetPatil** [comment]
Great!
