### ISSUE TITLE
v11.1 branch

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/docs#202]
The documentation for v11.1 should be extend by the new features like PK parameters calculation for populations.. is there already a fork/branch we can work on?

**Comment by msevestre** [comment]
This is done. PR only on v11.1 please . We will be able to see the edit live

**Comment by msevestre** [comment]
This will be the link for preview
https://open-systems-pharmacology.gitbook.io/v11.1/
