### ISSUE TITLE
11.1 Add deviation - wrong description

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/docs#207]
Adjust the docu and the screenshot after https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2383 was fixed

**Comment by georgeDaskalakis** [comment]
fixed

**Comment by georgeDaskalakis** [comment]
through commit:

https://github.com/Open-Systems-Pharmacology/docs/commit/5192da1358f6afc5b01f3d433164a5aa102b377e
