### ISSUE TITLE
Extend description of lin residuals

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/docs#211]
Under PI(https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification#mapping-simulation-outputs-to-observed-data) and in the GOF plots description: 
extend the description with the explanation, that linear residuals are always calculated in the **internal** units

![grafik](https://user-images.githubusercontent.com/25061876/201678589-5cdfd282-79f4-4752-98cb-5db517a589f5.png)

**Comment by georgeDaskalakis** [comment]
fixed through latest commit in v11 1.  @Yuri05 forgot to do a PR on this, sorry.
