### ISSUE TITLE
Offline Version of Documentation

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/docs#70]
I think it would make sense to still have the option to integrate an offline version of the documentation with the OSPSuite locally, as we are not always connected to the internet.

**Comment by msevestre** [comment]
There is a PDF version of the docs attached with the setup.   Is this what you are asking?

**Comment by StephanSchaller** [comment]
Ah, right. Forgot about that one.
Yeah, this should be fine.

**Comment by StephanSchaller** [comment]
But maybe it should be more obvious?
