### ISSUE TITLE
messed OSPS manual format

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/docs#75]
e.g. 
1. Table of Contents without hyperlinks
2. missing figures p. 22 ff
etc.

**Comment by msevestre** [comment]
>This Manual used to have e.g. hyperlinks, that disappeared in the 7.4 version.

Yes this is not the same manual. We generate the content from a complete different source and there is so much that can be implemented in that way.

**Comment by msevestre** [comment]
FYI: docs.open-systems-pharmacology.org is your friend

**Comment by msevestre** [comment]
Not relevant anymore as we are creating another type of pdf
