### ISSUE TITLE
GitBook-preview in PRs

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/docs#87]
It would be great to have a preview rendered by GitBook in every PR.

**Comment by msevestre** [comment]
I don't see how it would be possible. We would have to publish to another URL which would be very detrimental as far as SEO is concerned.

gitbook provides an edit mode (WYSISYG) but it messes the markup completely up. (at least that's what was happening last time I tried).

In general, image work great if they are not idented. I'd suggest to remove the indentation of the images to make sure they are full width

**Comment by msevestre** [comment]
@Yuri05 I have no time to look into that now.

**Comment by Yuri05** [comment]
>In general, image work great if they are not idented. I'd suggest to remove the indentation of the images to make sure they are full width

Interesting... will try

**Comment by Yuri05** [comment]
Indeed - removing indentations solved the problem. Cool! 
Good to know.
